/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const ContractAddresses_5 = {
  OvenueSeniorPool: '0x70Cd57E3DDf63c71CD5DF316eBb6570042ACd17C',
  OvenueConfig: '0x07C6AE1Cde8819a20BcB721326e76Af93B28bd4E',
  OvenueFactory: '0xB9C009E1B98e7adDE72F8364E3004962B0fCB478',
  OvenueJuniorPoolImpl: '0xf2c78dA8e56f651358eD3229929C15e43d79DeE9',
  OvenueJuniorLP: '0xCff0d8F115434AD0D6349B64DFC4ef798a8a247a',
  OvenueSeniorLP: '0x1ECDF068cb5A82eAbcd576C83B0dc475De4e833F',
  OvenueGo: '0x0eD723Ad5A65e358c51B249C31E508FC434089dA',
  OvenueUniqueIdentity: '0x6a0CB44728612072fa3EBD29dC6FE344A43ac326',
  OvenueCreditLine: '0x6cc2B0fa1e33E9946c081179098Dc0a8f637DeDE',
  OvenueJuniorRewards: '0x941c9f53c29Cd5E6f824AF09Ef885726a1211298',
  OvenueCollateralCustody: '0x8977f030B98b194fE3372cA6F0C2e4708578E6fE',
  OvenueSeniorStrategy: '0x0CF467e1D3Ec63beED87420EdA17B3038D78fbB7',
  USDC: '0xdf14a8B4D1cB5e838E6770A2960500058C9696a7'
}