/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractAddresses_4 } from './4'
import { ContractAddresses_5 } from './5'
export type ContractAddressesKey = keyof typeof ContractAddresses
export const ContractAddresses = {
  4: ContractAddresses_4,
  5: ContractAddresses_5
}